AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
  
Syntax/HashSyntax:
  EnforcedStyle: no_mixed_keys

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedLastArgumentHashStyle: ignore_implicit
