AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - node_modules/**/*

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/SymbolArray:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/BlockLength:
  ExcludedMethods:
    - describe
